services:
  alert:
    build:
      target: alert
    environment:
      RABBITMQ_ENV_FILE: /run/secrets/rabbitmq-env-config
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - rabbitmq-env-config
      - postgres-password
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  checker:
    build:
      target: checker
    environment:
      RABBITMQ_ENV_FILE: /run/secrets/rabbitmq-env-config
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - rabbitmq-env-config
      - postgres-password
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  scheduler:
    build:
      target: scheduler
    environment:
      RABBITMQ_ENV_FILE: /run/secrets/rabbitmq-env-config
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - rabbitmq-env-config
      - postgres-password
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  tgbot:
    build:
      target: tgbot
    environment:
      TELEGRAM_TOKEN_FILE: /run/secrets/telegram-token
      RABBITMQ_ENV_FILE: /run/secrets/rabbitmq-env-config
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - telegram-token
      - rabbitmq-env-config
      - postgres-password
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  rabbitmq:
    image: rabbitmq:4.0.8-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_CONF_ENV_FILE: /run/secrets/rabbitmq-env-config
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    secrets:
      - rabbitmq-env-config
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:17.4
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - postgres-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  migrator:
    build:
      target: migrator
    environment:
      DATABASE_DRIVER: postgres
      MIGRATIONS_FOLDER: migrations/postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - postgres-password
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  storage:
  rabbitmq:
  pgdata:

secrets:
  telegram-token:
    environment: TELEGRAM_TOKEN
  rabbitmq-env-config:
    file: ./rabbitmq-env.conf
  postgres-password:
    environment: POSTGRES_PASSWORD
